# Makefile

#
# $Id$
#
# $Log$
# Revision 1.1.1.1  2000/03/09 10:18:36  milo
# Initial import
#
# Revision 2.0  2000/01/19 07:21:25  milo
# Version 2.0
#
# Revision 1.1  1999/08/09 05:51:09  milo
# Added the abstract syntax tree (AST) parsing for the action
# description language
#
# Revision 1.22  1999/08/04 19:19:25  milo
# In the middle of changing everything.
#
# Revision 1.21  1999/07/23 21:57:57  dickson
# finshed converting to flat
#
# Revision 1.1.1.1  1999/07/02 07:11:21  milo
# Initial import
#
#


all:
	cd ..; $(MAKE) $@
ruby.exec:
	cd ..; $(MAKE) $@
Memory_tester.exec:
	cd ..; $(MAKE) $@
Directory_tester.exec:
	cd ..; $(MAKE) $@
EventQueue_tester.exec:
	cd ..; $(MAKE) $@
Vector_tester.exec:
	cd ..; $(MAKE) $@
Set_tester.exec:
	cd ..; $(MAKE) $@
RefCnt_tester.exec:
	cd ..; $(MAKE) $@
MessageQueue_tester.exec:
	cd ..; $(MAKE) $@
Network_tester.exec:
	cd ..; $(MAKE) $@
state_machine/generator:
	cd ..; $(MAKE) $@
memory/DirectoryMachine.C:
	cd ..; $(MAKE) $@
memory/DirectoryState.C:
	cd ..; $(MAKE) $@
memory/DirectoryState.h:
	cd ..; $(MAKE) $@
memory/DirectoryEvent.h:
	cd ..; $(MAKE) $@
memory/DirectoryEvent.C:
	cd ..; $(MAKE) $@
processor/CacheMachine.C:
	cd ..; $(MAKE) $@
processor/CacheEvent.C:
	cd ..; $(MAKE) $@
processor/CacheEvent.h:
	cd ..; $(MAKE) $@
processor/CacheState.C:
	cd ..; $(MAKE) $@
processor/CacheState.h:
	cd ..; $(MAKE) $@
.c.o:
	cd ..; $(MAKE) $@
.C.o:
	cd ..; $(MAKE) $@
.y.c:
	cd ..; $(MAKE) $@
.l.c:
	cd ..; $(MAKE) $@
clean:
	cd ..; $(MAKE) $@
tags:
	cd ..; $(MAKE) $@
depend:
	cd ..; $(MAKE) $@
# DO NOT DELETE

bcast-simple/TBETable.o: TBETable.h ../global.h ../Vector.h ../global.h
bcast-simple/TBETable.o: ../global.h ../Vector.h ../global.h
